// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }







// import "./globals.css";
// import Navbar from "@/components/Navbar";
// import Footer from "@/components/Footer";

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body>
//         <Navbar />
//         {children}
//         <Footer />
//       </body>
//     </html>
//   );
// }











// import "./globals.css";
// import TopBar from "@/components/TopBar";
// import Navbar from "@/components/Navbar";
// import Footer from "@/components/Footer";

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body>
//         <TopBar />
//         <Navbar />
//         {children}
//         <Footer />
//       </body>
//     </html>
//   );
// }









// import "./globals.css";
// import TopBar from "@/components/TopBar";
// import Navbar from "@/components/Navbar";
// import Footer from "@/components/Footer";

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body>

//         {/* Fixed Header */}
//         <header className="sticky top-0 z-50">

//           {/* Red Top Bar */}
//           <TopBar />

//           {/* White Navbar */}
//           <Navbar />

//         </header>

//         {/* Page Content */}
//         {children}

//         {/* Footer */}
//         <Footer />

//       </body>
//     </html>
//   );
// }





// import "./globals.css";
// import TopBar from "@/components/TopBar";
// import Navbar from "@/components/Navbar";
// import Footer from "@/components/Footer";
// import Popup from "@/components/Popup";

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body>

//         <Popup />

//         <TopBar />
//         <Navbar />

//         {children}

//         <Footer />

//       </body>
//     </html>
//   );
// }


import "./globals.css";
import TopBar from "@/components/TopBar";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Popup from "@/components/Popup";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>

        {/* Fixed Header */}
        <header className="sticky top-0 z-50">
        <Popup />
          {/* Red Top Bar */}
          <TopBar />

          {/* White Navbar */}
          <Navbar />

        </header>

        {/* Page Content */}
        {children}

        {/* Footer */}
        <Footer />

      </body>
    </html>
  );
}